nginx:
  image: nginx
  links:
    - app
  ports:
    - "80:80"

app:
  build: .
  links:
    - mongo
    - redis
  ports:
   - "3000:3000"

mongo:
  image: mongo
  command: mongod --smallfiles --quiet --logpath=/dev/null

redis:
  image: redis
  ports:
    - "6379"
