app:
  build: .
  links:
    - mongo
    - redis
  ports:
    - "80:3000"
    - "3001:3001"
  environment:
    - DEBUG=*

mongo:
  image: mongo
  ports:
    - "27017"

redis:
  image: redis
  ports:
    - "6379"
