nginx:
  links:
    - app
  ports:
    - "80:80"

app:
  image: node:0.10
  command: node app.js
  links:
    - mongo
    - redis
  volumes:
    - ./:/ui-builder-app
  ports:
   - "3000:3000"

mongo:
  image: mongo
  command: mongod --smallfiles --quiet --logpath=/dev/null

redis:
  image: redis
  ports:
    - "6379"
